### ISSUE TITLE
请问可以自己在caffe-ssd训练模型然后通过tools中工具转换为ncnn格式么？

### ISSUE THREAD

**Issue by HansRen1024** [arlose/ncnn-mobilenet-ssd#7]
请问可以自己在caffe-ssd训练模型然后通过tools中工具转换为ncnn格式么？
我尝试转换了一下，用不了呢。乱七八糟的框。

**Comment by HansRen1024** [comment]
搞定了。原来要用整合过bn参数和conv参数的deplot.caffemodel，不能用训练好的模型。

**Comment by immarioo** [comment]
> 
> 
> 搞定了。原来要用整合过bn参数和conv参数的deplot.caffemodel，不能用训练好的模型。

你好，请问下你尝试过pytorch的模型转ncnn然后测试吗？我看ssdmobilenet.param和代码中只需要extract一个值detection_out就可以了，转模型的时候是要把prob和loc都concat到一起吗？

**Comment by HansRen1024** [comment]
> > 搞定了。原来要用整合过bn参数和conv参数的deplot.caffemodel，不能用训练好的模型。
> 
> 你好，请问下你尝试过pytorch的模型转ncnn然后测试吗？我看ssdmobilenet.param和代码中只需要extract一个值detection_out就可以了，转模型的时候是要把prob和loc都concat到一起吗？

抱歉，我不了解pytorch和ncnn转换。已经没接触ncnn一年多了。

**Comment by immarioo** [comment]
> 
> 
> > > 搞定了。原来要用整合过bn参数和conv参数的deplot.caffemodel，不能用训练好的模型。
> > 
> > 
> > 你好，请问下你尝试过pytorch的模型转ncnn然后测试吗？我看ssdmobilenet.param和代码中只需要extract一个值detection_out就可以了，转模型的时候是要把prob和loc都concat到一起吗？
> 
> 抱歉，我不了解pytorch和ncnn转换。已经没接触ncnn一年多了。

谢谢回复，我大概找到方法了，等我慢慢摸索下。
